#!/usr/bin/sh

# must be placed in the .git/hook directory with the name "pre-commit" and have execution permission

echo "////"
echo "Automatic detection of modified but unbuilt typst files..."

root=$(git rev-parse --show-toplevel)
diffs=$(git diff --cached --name-only --diff-filter=d -- '*.typ')

if [ -z "$diffs" ]; then
    echo "No typst file modified"
    echo "////"
    exit 0
fi

echo "Found modified typst files:"
echo $diffs

echo "Building these files..."
for file in $diffs
do
    typst compile "$root/$file" --root $root
    git add "$root/${file%.*}.pdf"
done

echo done.
echo "////"
exit 0